---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: silverfox
# description will be included in the image's metadata
description: A more vanilla GNOME experience, but also good for light customisations.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/monkeygold/nautilus-open-any-terminal/repo/fedora-%OS_VERSION%/monkeygold-nautilus-open-any-terminal-fedora-%OS_VERSION%.repo
    install:
      - gnome-console
      - libgda # for Pano
      - libgda-sqlite # for Pano
      - nautilus-open-any-terminal # to make GNOME Console work on Fedora
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - htop
      - nvtop
      - ptyxis 
      
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.gnome.Epiphany
        - org.gnome.Loupe
        - org.gnome.Papers
        - org.gnome.Showtime
        - org.gnome.Decibels
        - org.gnome.TextEditor
        - org.gnome.Snapshot
        - org.gnome.Calculator
        - org.gnome.clocks
        - org.gnome.Calendar
        - org.gnome.Weather
        - org.gnome.Maps
        - org.gnome.font-viewer
        - org.gnome.Characters
        - org.gnome.baobab
      remove:
        - org.gnome.eog
        - org.gnome.Evince
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

